### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by in10se** [Lunyr/crowdsale-contracts#4]
The source code won't compile. I get the following error:

> truffle compile && truffle migrate
> Compiling ./contracts/ERC20.sol...
> Compiling ./contracts/LunyrToken.sol...
> Compiling ./contracts/Migrations.sol...
> Compiling ./contracts/MultiSigWallet.sol...
> Compiling ./contracts/NewToken.sol...
> Compiling ./contracts/SafeMath.sol...
> Compiling ./contracts/TestContract.sol...
> 
> Compilation warnings encountered:
> 
> /home/user/Projects/Ethereum/crowdsale-contracts-master/contracts/LunyrToken.sol:85:48: : Initial value for constant variable has to be compile-time constant. This wil
> l fail to compile with the next breaking version change.
>     uint256 public constant tokenCreationMax = safeMul(250000 ether, tokensPerEther);
>                                                ^-----------------------------------^
> ,/home/user/Projects/Ethereum/crowdsale-contracts-master/contracts/LunyrToken.sol:86:48: : Initial value for constant variable has to be compile-time constant. This wi
> ll fail to compile with the next breaking version change.
>     uint256 public constant tokenCreationMin = safeMul(25000 ether, tokensPerEther);
>                                                ^----------------------------------^
> 
> 
> /home/user/Projects/Ethereum/crowdsale-contracts-master/contracts/LunyrToken.sol:85:48: : Initial value for constant variable has to be compile-time constant. This wil
> l fail to compile with the next breaking version change.
>     uint256 public constant tokenCreationMax = safeMul(250000 ether, tokensPerEther);
>                                                ^-----------------------------------^
> ,/home/user/Projects/Ethereum/crowdsale-contracts-master/contracts/LunyrToken.sol:86:48: : Initial value for constant variable has to be compile-time constant. This wi
> ll fail to compile with the next breaking version change.
>     uint256 public constant tokenCreationMin = safeMul(25000 ether, tokensPerEther);
>                                                ^----------------------------------^
> ,/home/user/Projects/Ethereum/crowdsale-contracts-master/contracts/LunyrToken.sol:113:21: : Contract with internal constructor cannot be created directly.
>         timeVault = new LUNVault(_lunyrMultisig);
>                     ^----------^
> Compiliation failed. See above.

**Comment by illuzen** [comment]
This is due to your newer compiler. Simply replace the constant variables with actual constants and remove the internal descriptor from the LUNVault constructor. Wanna make a PR?

**Comment by in10se** [comment]
Thanks, that fixed it. What do you mean by PR?On Jun 6, 2017 1:00 PM, illuzen <notifications@github.com> wrote:This is due to your newer compiler. Simply replace the constant variables with actual constants and remove the internal descriptor from the LUNVault constructor. Wanna make a PR?

**Comment by illuzen** [comment]
PR == Pull Request.

You can fork the repository, modify the code, push it to your fork, then make a pull request thru GitHub and I'll accept it and you will have public credit that you contributed to this repository. If you want.

**Comment by in10se** [comment]
Ok, sure, I'll do that. Thanks for explaining.On Jun 6, 2017 3:44 PM, illuzen <notifications@github.com> wrote:PR == Pull Request.
You can fork the repository, modify the code, push it to your fork, then make a pull request thru GitHub and I'll accept it and you will have public credit that you contributed to this repository. If you want.
